openapi: 3.0.0
info:
  title: APIs exposed by Service Providers for Bank iD
  version: 2.0.4
  description: |
    Describes APIs exposed by Service Providers for Bank iD. Changelog available at [GitHub](https://github.com/BankovniIdentita/bankid-api-docs/tree/main/sep-for-bankid).

paths:
  /back-channel/logout:
    post:
      description: >-
        Logout endpoint specified in [OpenID.BackChannelLogout](https://openid.net/specs/openid-connect-backchannel-1_0.html).
      tags:
        - Back-Channel Logout
      operationId: backChannelLogout
      parameters:
        - in: header
          name: traceId
          schema:
            $ref: '#/components/schemas/traceId'
      requestBody:
        required: true
        description: JWT containing JSON as payload. [Back-Channel Logout API documentation](https://developer.bankid.cz/docs/apis_sep#back-channel-logout-api).
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BackLogoutRequest'
      responses:
        '200':
          description: Logout successful
          headers:
            traceId:
              description: Unique ID for each API call for support purposes.
              schema:
                $ref: '#/components/schemas/traceId'
        '400':
          description: Logout request was invalid
          headers:
            traceId:
              description: Unique ID for each API call for support purposes.
              schema:
                $ref: '#/components/schemas/traceId'
        '500':
          description: Logout has failed
          headers:
            traceId:
              description: Unique ID for each API call for support purposes.
              schema:
                $ref: '#/components/schemas/traceId'
        '504':
          description: Logout succeeded but some downstream logouts have failed
          headers:
            traceId:
              description: Unique ID for each API call for support purposes.
              schema:
                $ref: '#/components/schemas/traceId'


  /notify:
    post:
      description: >-
        Batch notification endpoint which accepts a list of notification tokens. These are mainly claim update notifications.
      tags:
        - Notifications
      operationId: getNotifications
      parameters:
        - in: header
          name: traceId
          schema:
            $ref: '#/components/schemas/traceId'
      requestBody:
        required: true
        description: JWT contating JSON as payload.
        content:
          application/jwe:
            schema:
              $ref: '#/components/schemas/NotificationRequest'
      responses:
        '200':
          description: Notification batch accepted successfully
          headers:
            traceId:
              description: Unique ID for each API call for support purposes.
              schema:
                $ref: '#/components/schemas/traceId'

components:
  schemas:
    traceId:
      description: Unique ID for each API call for support purposes.
      type: string
      pattern: '^[a-zA-Z0-9]{16}$'
      example: 26f6ea6095205ebc
    NotificationRequest:
      externalDocs:
        description: '[OpenID.BackChannelLogout] 2.4. Logout Token'
        url: 'https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken'
      description: >-
        Signed and encrypted JWT which serves as a vessel for notification events.
        (Encryption is only applied if SeP has encryption set for the application and has configured a JWKS endpoint in the developer portal)
      type: object
      required:
        - iss
        - iat
        - jti
        - events
      properties:
        iss:
          type: string
          description: >-
            Issuer Identifier for the Issuer of the response.
            The iss value is a case sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components.
          example: https://idp.example.com
        iat:
          type: number
          format: int64
          description: Time at which the JWT was issued. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.
          example: 1582797458
        jti:
          type: string
          description: >-
            JWT ID. A unique identifier for the token, which can be used to prevent reuse of the token.
            These tokens MUST only be used once, unless conditions for reuse were negotiated between the parties; any such negotiation is beyond the scope of this specification
          example: 913CC0F7-27BA-40D9-9F4F-8DF74AC3596B
        events:
          description: An array of notification events
          type: array
          items:
            $ref: '#/components/schemas/NotificationEvent'

    BackLogoutRequest:
      externalDocs:
        description: '[OpenID.BackChannelLogout] 2.4. Logout Token'
        url: 'https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken'
      description: >-
        JWT containing JSON as payload. [Back-Channel Logout API documentation](https://developer.bankid.cz/docs/apis_sep#back-channel-logout-api).
      type: object
      required:
        - logout_token
      properties:
        logout_token:
          type: string
          description: >-
            Signed and encrypted JWT
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

    NotificationEvent:
      description: >-
        An event describing a change. It is possible to filter the specificity of the event using the `affected_` filters.
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - claims_updated
          description: >-
            - claims_updated: A claim has changed. `affected_subs` is mandatory,
                            `affected_claims` is possible to supply as well, depending on the business case
          example: claim_updated
        original_event_at:
          type: string
          format: date-time
          description: >-
            What is the original time that this event has happened at
        sub:
          type: string
          format: uuid
          description: >-
            Affected sub
          example: '9456B875-62D3-4533-A502-E05D39936F3A'
        affected_client_ids:
          type: array
          items:
            type: string
            format: uuid
          description: >-
            An optional array of affected client_ids
          example: ['F932FF05-E04C-4CD1-86E4-CE82F1F51EFB']
        affected_claims:
          type: array
          items:
            type: string
          description: |
            An optional array of modified claims. This is relevant for `type` of `claims_updated`. 

            Supported values: 
              `sub`, `claims_updated`, `birthdate`, `date_of_death`, `email`, `email_verified`, `locale`, `name`, `given_name`, `family_name`, `middle_name`, `nickname`, `preferred_username`, `phone_number`, `phone_number_verified`, `updated_at`, `zoneinfo`, `addresses`, `birthnumber`, `gender`, `paymentAccounts`, `paymentAccountsDetails`, `title_prefix`, `title_suffix`, `birthplace`, `birthcountry`, `primary_nationality`, `nationalities`, `idcards`, `majority`, `pep`, `limited_legal_capacity`, `maritalstatus`, `trust_framework`, `time`, `verification_process`
          example: ['phone_number', 'addresses', 'idcards']
